#!/bin/bash

# shellcheck disable=all

if [[ -t 1 ]]
then
  declare -rg ESCAPE=""
  declare -rg STOP_COLOR="${ESCAPE}[0m"
  declare -rg RED="${ESCAPE}[0;31m"
  declare -rg YELLOW="${ESCAPE}[1;33m"
  declare -rg GREEN="${ESCAPE}[0;32m"
fi

PATH=${PATH}:${HOME}/scripts/power-shell/misc
ps1-wrapper update-pom-version.ps1 -Version 4.5.6-SNAPSHOT | \
grep -Ev '(^$|\[ps1-wrapper)'                              | \
sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/"                  | \
sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/"           | \
sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"

