#!/bin/bash

# shellcheck disable=all

if [[ -t 1 ]]
then
  declare -rg ESCAPE=""
  declare -rg STOP_COLOR="${ESCAPE}[0m"
  declare -rg RED="${ESCAPE}[0;31m"
  declare -rg YELLOW="${ESCAPE}[1;33m"
  declare -rg GREEN="${ESCAPE}[0;32m"
fi

##ps1-wrapper ${HOME}/scripts/power-shell/misc/artifacts-array.ps1 -Array MOCKITO_COOKBOOK_ARTIFACTS
ps1-wrapper ${HOME}/scripts/power-shell/misc/artifacts-array.ps1 | \
grep -Ev '(^$|\[ps1-wrapper)'                                    | \
sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/"                        | \
sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/"                 | \
sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"
