#!/bin/bash

# shellcheck disable=all

function cr8_target_pom
{
  rm -rf "${1}"/target
  mkdir "${1}"/target
  cp "${1}"/pom.xml "${1}"/target
}

targets+=" chapter01"
targets+=" chapter02"
targets+=" common"
targets=${targets# }

for target in ${targets}
do
  cr8_target_pom "${target}"
done

ps1-wrapper ${HOME}/scripts/power-shell/misc/pom-versions.ps1

for target in ${targets}
do
  rm -rf "${target}"/target
done

