#!/bin/bash

./scr1
while IFS= read -r pom
do
  echo "===== BEGIN [${pom}] ====="
  ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile "${pom}"
  echo "=====  END  [${pom}] ====="
  echo ''
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \))"

##git checkout xsd/maven-4.0.0.xsd > /dev/null 2>&1
##ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile xsd/maven-4.0.0.xsd

git status

