#!/bin/bash

# shellcheck disable=all
source ~/.dotfiles/xml_functions

while IFS= read -r pom
do
  beautify_xml_with_xmllint "${pom}" 'Maven BOM/POM schema file'
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \))"

