#!/bin/bash

# shellcheck disable=all
source ~/.dotfiles/xml_functions

./scr1
while IFS= read -r pom
do
  echo "===== BEGIN [${pom}] ====="
  beautify_xml_with_xmllint "${pom}" 'Maven BOM/POM file'
##  beautify_xml_with_xmlstarlet "${pom}" 'Maven BOM/POM file'
##  beautify_xml_with_xmlindent "${pom}" 'Maven BOM/POM file'
  echo "=====  END  [${pom}] ====="
  echo ''
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \) | sort)"

##git checkout xsd/maven-4.0.0.xsd > /dev/null 2>&1
##beautify_xml_with_xmllint xsd/maven-4.0.0.xsd 'Maven BOM/POM schema file'

git status

