#!/bin/bash

# shellcheck disable=all

if [[ -t 1 ]]
then
  declare -rg ESCAPE=""
  declare -rg STOP_COLOR="${ESCAPE}[0m"
  declare -rg RED="${ESCAPE}[0;31m"
  declare -rg YELLOW="${ESCAPE}[1;33m"
  declare -rg GREEN="${ESCAPE}[0;32m"
fi

rm -f dtd/pom.xml

while IFS= read -r pom
do
  echo "===== BEGIN [${pom}] ====="
  ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile "${pom}" -Schema maven-4.0.0.xsd | \
  grep -Ev '(^$|\[ps1-wrapper)'                                                                 | \
  sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/"                                                     | \
  sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/"                                              | \
  sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"
  echo "=====  END  [${pom}] ====="
  echo ''
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \) | sort)"

