#!/bin/bash

# shellcheck disable=all

# "de-formats" pom files

declare -i has_crlf=0

while IFS= read -r pom
do
  file "${pom}" | grep -q ' CRFL '
  has_crlf=${?}
  if [[ 0 -eq ${has_crlf} ]]
  then
    dos2unix "${pom}" > /dev/null 2>&1
  fi
  sed -i 's/$/                  /'               "${pom}"
  sed -i 's/<groupId>/               <groupId>/' "${pom}"
  sed -i 's/<artifactId>/ <artifactId>/'         "${pom}"
  sed -i 's/<modules>/         <modules>/'       "${pom}"
  sed -i 's|<name></name>|<name/>|'              "${pom}"
  sed -i 's/^ *<dependency>/<dependency>/'       "${pom}"
  if [[ 0 -eq ${has_crlf} ]]
  then
    unix2dos "${pom}" > /dev/null 2>&1
  fi
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \))"

