#!/bin/bash

# shellcheck disable=all

# removes encoding from xml declaration

while IFS= read -r pom
do
  sed -i '1s|<?xml version="1.0" encoding="UTF-8"?>|<?xml version="1.0"?>|' "${pom}"
done <<< "$(find . -not -path "*/dtd/*" -type f \( -name "*\.pom" -o -name "pom\.xml" \))"

