#!/bin/bash

# shellcheck disable=all

while IFS= read -r pom
do
  sed -i '1s|<?xml version="1.0" encoding="utf-8"?>|<?xml version="1.0"?>|' "${pom}"
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \))"

