#!/bin/bash

declare -r SCRIPT=${0##*/}

# ${1} - array indexed with integers
# ${2} - label (optional)
function print_int_array
{
  local -r label=${2:-${1}}
  local -n array=${1}
  local -i i=0
  echo "${label} size = [${#array[@]}]"
  for ((i = 0; i < ${#array[@]}; i++))
  do
    echo "${label}[${i}] = [${array[${i}]}]" | sed 's/=/;/g'
  done | column -s"=" -o"=" -t | sed 's/;/=/g'
}

# ${1} - xsd file
# ${2} - file type
function sort_schema_attributes
{
  local -r file_type="${2}"
  local -r command=sed
  command -v "${command}" > /dev/null
  local -i stat=${?}
  if [[ 0 -ne ${stat} ]]
  then
    log_warning "The command [${command}] was not found; can not sort schema tag attributes in [${file_type}] file [${1}]." "${LINENO}"
    return 0
  fi

  grep -q '^<xs:schema .*[^>]$' "${1}"
  local -i stat=${?}
  if [[ 0 -eq ${stat} ]]
  then
################################################################################
# Joining split <xs:schema> tokens.                                            #
################################################################################
    "${command}" -i -E '
################################################################################
# Detect the start of a split <xs:schema ... line (not ending with ">").       #
################################################################################
      /^<xs:schema [^>]*$/ {
        :join
################################################################################
# Read the next line into the pattern space.                                   #
################################################################################
          N
################################################################################
# Trim leading spaces after the newline.                                       #
################################################################################
          s/\n[[:space:]]+/ /
################################################################################
# If it still does not end with ">", keep joining.                             #
################################################################################
          />$/! b join
      }
    ' "${1}"
    stat=${?}
    if [[ 0 -ne ${stat} ]]
    then
      log_error "Failed to join split [xs:schema] lines in [${file_type}] file [${1}] due to error code [${stat}]" "${LINENO}"
      return "${stat}"
    fi
  fi

################################################################################
# Sorting <xs:schema> tokens.                                                  #
################################################################################
  local -a attributes
  mapfile -t attributes < <(grep '^<xs:schema .*>$' "${1}" | "${command}" 's/>$//;s/   */ /g;s/ /\n/g')
##  print_int_array attributes
  local schema_line
  local xmlns
  local -i i=1
  for ((i = 1; i < ${#attributes[@]}; i++))
  do
    if [[ "${attributes[${i}]}" =~ ^xmlns ]]
    then
      xmlns+=" ${attributes[${i}]}"
    else
      schema_line+=" ${attributes[${i}]}"
    fi
  done
  xmlns=$(echo "${xmlns}" | tr ' ' '\n' | sort | paste -sd' ')
  schema_line=$(echo "${schema_line}" | tr ' ' '\n' | sort | paste -sd' ')
  schema_line="${attributes[0]} ${xmlns# } ${schema_line# }>"
  "${command}" -i "s|^<xs:schema .*>$|${schema_line}|" "${1}"
  stat=${?}
  if [[ 0 -ne ${stat} ]]
  then
    log_error "Failed to sort attributes for [xs:schema] in [${file_type}] file [${1}] due to error code [${stat}]." "${LINENO}"
  fi
  return "${stat}"
}

while [[ -n "${1}" ]]
do
  sort_schema_attributes "${1}"
  shift 1
done

