#!/bin/bash

declare -r SCRIPT=${0##*/}

function set_color_variables
{
  if [[ ! -v ESCAPE ]]
  then
    declare -rg ESCAPE=""
  fi
  if [[ ! -v STOP_COLOR ]]
  then
    declare -rg STOP_COLOR="${ESCAPE}[0m"
  fi
  if [[ ! -v RED ]]
  then
    declare -rg RED="${ESCAPE}[0;31m"
  fi
  if [[ ! -v YELLOW ]]
  then
    declare -rg YELLOW="${ESCAPE}[1;33m"
  fi
  if [[ ! -v GREEN ]]
  then
    declare -rg GREEN="${ESCAPE}[0;32m"
  fi
}

# ${1} - message
# ${2} - message level
# ${3} - line number (optional)
function log_message
{
  local message_level=${2}
  if [[ -t 1 ]]
  then
    case ${2} in
      ERROR   ) message_level=${RED}${message_level}${STOP_COLOR};;
      WARNING ) message_level=${YELLOW}${message_level}${STOP_COLOR};;
      INFO    ) message_level=${GREEN}${message_level}${STOP_COLOR};;
      *       ) :;;
    esac
  fi

################################################################################
# NOTE: Want to replace the value of the HOME environment variable with the    #
#       literal string '${HOME}' in the message.                               #
################################################################################
  local message="${message_level}: ${1//${HOME}/\$\{HOME\}}"
  message="${message//${USER}/\$\{USER\}}"
  if [[ -n "${3}" ]]
  then
    message="Line = [${3}] ${message}"
  fi
  echo "[${SCRIPT}] ${message}"
  return 0
}

# ${1} - error message
# ${2} - line number (optional)
function log_error
{
  log_message "${1}" ERROR "${2}"
  return 0
}

# ${1} - warning message
# ${2} - line number (optional)
function log_warning
{
  log_message "${1}" WARNING "${2}"
  return 0
}

# ${1} - info message
# ${2} - line number (optional)
function log_info
{
  log_message "${1}" INFO "${2}"
  return 0
}

# Sets and checks the platform
function set_platform
{
  local platform=$(uname)
  case ${platform} in
    CYGWIN_NT-*  ) log_error "[PowerShell] is not supported on [cygwin]. Exiting." "${LINENO}"
                   exit 1;;
    MINGW64_NT-* ) PLATFORM="git-bash"
################################################################################
# Cygwin binaries do not always work under git-bash. Therefore, all cygwin64   #
# bin directories are removed from the PATH environment variable.              #
################################################################################
                   PATH=$(echo "${PATH}" | tr ':' '\n' | grep -v "^/[a-z]/cygwin64/.*bin$" | tr '\n' ':')
                   PATH="${PATH%:}";;
    Linux        ) PLATFORM="linux";;
    *            ) log_error "The platform [${platform}] is not recognized. Exiting." "${LINENO}"
                   echo ''
                   exit 1;;
  esac
  declare -rg PLATFORM="${PLATFORM}"
  return 0
}

# ${1} - command to be checked
function check_command
{
  command -v "${1}" > /dev/null
  local -i stat=${?}
  return "${stat}"
}

# ${1} - Apache schema file url
# ${2} - schema file number
function get_apache_schema
{
  local -r xsd="$(basename "${1}")"
  local schema="${APACHE_SCHEMAS_URL}${xsd}"
  "${CURL}" "${schema}" 2> /dev/null | sed 's@^<?xml version="1.0"?>$@<?xml version="1.0" encoding="UTF-8"?>@' >| "${xsd}"
  local -i stat=${PIPESTATUS[0]}
  if [[ 0 -ne ${?} ]]
  then
    echo "[${SCRIPT}] ERROR: Could not download schema [${schema}] due to error code [${stat}]."
    rm -f "${xsd}"
  else
    log_info "Downloaded schema number [${2}] [${1}]." "${LINENO}"
    dos2unix "${xsd}" > /dev/null 2>&1
    beautify_xml_with_xmlstarlet "${xsd}" XSD
  fi
  echo ''
}

function get_apache_schemas
{
  local -a schemas
  mapfile -t schemas < <(${CURL} --silent "${APACHE_SCHEMAS_URL}" 2> /dev/null | grep -oP '(?<=href=")[^"]+\.xsd' | grep -Ev -e "-(alpha|beta|rc)-" | sed "s@^@${APACHE_SCHEMAS_URL}@")
  local -i i=0
  for ((i = 0; i < ${#schemas[@]}; i++))
  do
    get_apache_schema "${schemas[${i}]}" $((${i} + 1))
  done
}

function set_variables
{
  source ~/.dotfiles/xml_functions
  declare -rg CURL=curl
  check_command "${CURL}"
  local -i stat=${?}
  if [[ 0 -ne ${stat} ]]
  then
    log_error "The command [${CURL}] was not found; can not download Apache schema files. Exiting." "${LINENO}"
    exit 1
  fi

  set_color_variables
  set_xml_linter_command
  set_xml_beautifier_command
  declare -rg APACHE_SCHEMAS_URL=https://maven.apache.org/xsd/
  declare -rg INDENT_SPACES="  "
  echo ''
}

################################################################################
# "main"                                                                       #
################################################################################
set_platform
set_variables
if [[ 0 -eq ${#} ]]
then
  get_apache_schemas
else
  declare -i index=1
  while [[ -n "${1}" ]]
  do
    get_apache_schema "${1}" "${index}"
    index=$((${index} + 1))
    shift 1
  done
fi

