#!/bin/bash

# shellcheck disable=all

git reset build.xml buildi_no_doctype.xml > /dev/null

if [[ -t 1 ]]
then
  declare -rg ESCAPE=""
  declare -rg STOP_COLOR="${ESCAPE}[0m"
  declare -rg RED="${ESCAPE}[0;31m"
  declare -rg YELLOW="${ESCAPE}[1;33m"
  declare -rg GREEN="${ESCAPE}[0;32m"
fi

# ${1} - ant build.xml
# ${1} - schema
function pwsh_validate_ant
{
  echo "===== BEGIN [${1}] [${2}] ====="
  sed -i 's@\(^ *\)\(<\)\([a-z]\+\)\( [a-z]\+.*\)\(/>$\)@\1\2\3\4></\3>@' "${1}"
  sed -i 's/^ *//' "${1}"
  ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile "${1}" -Schema "${2}" | grep -Ev "(ps1-wrapper|^$)" | \
  sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/" | sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/" | sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"

  ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile "${1}" | grep -Ev "(ps1-wrapper|^$)" | \
  sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/" | sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/" | sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"
  echo "=====  END  [${1}] [${2}] ====="
  echo ''
}

# ${1} - ant build.xml
# ${1} - schema
function validate_ant
{
  echo "===== BEGIN [${1}] [${2}] ====="
  sed -i 's@\(^ *\)\(<\)\([a-z]\+\)\( [a-z]\+.*\)\(/>$\)@\1\2\3\4></\3>@' "${1}"
  sed -i 's/^ *//' "${1}"
  validate_against_schema_with_xmllint "${1}" "${2}" | \
  sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/" | sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/" | sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"

  beautify_xml_with_xmllint "${1}" 'Maven BOM/POM file' | \
  sed "s/INFO:/${GREEN}INFO${STOP_COLOR}:/" | sed "s/WARNING:/${YELLOW}WARNING${STOP_COLOR}:/" | sed "s/ERROR:/${RED}ERROR${STOP_COLOR}:/"
  echo "=====  END  [${1}] [${2}] ====="
  echo ''
}

pwsh_validate_ant build.xml ant.xsd
pwsh_validate_ant build.xml ant.dtd
pwsh_validate_ant buildi_no_doctype.xml ant.xsd
pwsh_validate_ant buildi_no_doctype.xml ant.dtd

source ~/.dotfiles/xml_functions
validate_ant build.xml ant.xsd
validate_ant buildi_no_doctype.xml ant.xsd
##validate_ant build.xml ant.dtd
##validate_ant buildi_no_doctype.xml ant.dtd

git status build.xml buildi_no_doctype.xml

