#!/bin/bash

# shellcheck disable=all

file=build.xml
git reset "${file}" > /dev/null

sed -i 's@\(^ *\)\(<\)\([a-z]\+\)\( [a-z]\+.*\)\(/>$\)@\1\2\3\4></\3>@' "${file}"
ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile "${file}"
ps1-wrapper ~/scripts/power-shell/utilities-xml.ps1 -XmlFile "${file}" -Schema ant.xsd

source ~/.dotfiles/xml_functions
sed -i 's@\(^ *\)\(<\)\([a-z]\+\)\( [a-z]\+.*\)\(/>$\)@\1\2\3\4></\3>@' "${file}"
beautify_xml_with_xmllint "${file}" 'Maven BOM/POM file'
validate_against_schema_with_xmllint "${file}" ant.xsd

set -x
git status "${file}"
set +x

