#!/bin/bash

# shellcheck disable=all
SCHEMAS=${HOME}/.git_template/.git_hooks_dev/pre_commit/schemas

set -x
xmlstarlet validate --quiet --dtd ${SCHEMAS}/ant.dtd build.xml
stat=${?}
set +x
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

set -x
xmllint --noout --dtdvalid ${SCHEMAS}/ant.dtd build.xml
stat=${?}
set +x
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

ps1-wrapper ${HOME}/scripts/power-shell/utilities-xml.ps1 -XmlFile ${PWD}/build.xml -Schema "${SCHEMAS}/ant.xsd" -FileType "Ant build"
stat=${?}
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

ps1-wrapper ${HOME}/scripts/power-shell/utilities-xml.ps1 -XmlFile ${PWD}/build.xml -Schema "${SCHEMAS}/ant.dtd" -FileType "Ant build"
stat=${?}
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

ps1-wrapper ${HOME}/scripts/power-shell/utilities-xml.ps1 -XmlFile ${PWD}/build_nodoc.xml -Schema "${SCHEMAS}/ant.dtd" -FileType "Ant build"
stat=${?}
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

##export PRE_COMMIT_POWER_SHELL_XML_VALIDATOR=./${HOME}/scripts/power-shell/utilities-xml.ps1
##export PRE_COMMIT_XML_VALIDATOR_COMMAND=${PRE_COMMIT_POWER_SHELL_XML_VALIDATOR}
##cp ${PWD}/build.xml ${PWD}/build.xml_docbak
##cp ${PWD}/build_nodoc.xml ${PWD}/build.xml
##../../../pre-commit ${PWD}/build.xml
##stat=${?}
##echo "LINE = [${LINENO}] stat = [${stat}]"
##mv ${PWD}/build.xml_docbak ${PWD}/build.xml
##echo '--------------------------------------------------------------------------------'
##echo ''

