#!/bin/bash

# shellcheck disable=all

./upom
sed -i 's@<!-- <versionqq/> -->@<versionqq/>@' pom.xml
sed -i 's@<!-- <propertiesqq/> -->@<propertiesqq/>@' pom.xml

ps1-wrapper ${HOME}/scripts/power-shell/utilities-xml.ps1 -XmlFile ${PWD}/pom.xml -Schema ${PWD}/maven-4.0.0.xsd -FileType "Ant build"
stat=${?}
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

