#!/bin/bash

# shellcheck disable=all

if [[ -t 1 ]]
then
  clear
fi

./upom
sed -i 's@<!-- <versionqq/> -->@<versionqq/>@' pom.xml
sed -i 's@<!-- <propertiesqq/> -->@<propertiesqq/>@' pom.xml

ps1-wrapper ./val1.ps1
stat=${?}
echo "LINE = [${LINENO}] stat = [${stat}]"
echo '--------------------------------------------------------------------------------'
echo ''

