#!/bin/bash

# shellcheck disable=all

file=maven-4.0.0.xsd
git checkout "${file}" > /dev/null 2>&1
source ~/.dotfiles/xml_functions
sed -i 's|\(^.*\)\(<xs:documentation source=".*">$\)|\1   \t\t\t   \t\t\2|'  "${file}"
sed -i 's|\(^ *\)\(</xs:documentation>$\)|   \t\t\t   \t\t\2|'  "${file}"

beautify_xml_with_xmllint "${file}" 'Maven BOM/POM schema file'

