#!/usr/bin/gawk -f

################################################################################
# Properly indents <xs:documentation ...>, </xs:documentation> blocks.         #
################################################################################
BEGIN {
  in_xs_doc = 0
  xs_doc_indent = ""
}
{
  if ((0 != match($0, /^\s*<xs:documentation.*<\/xs:documentation>$/)) || (0 != match($0, /^\s*<xs:documentation .*\/>$/)))
  {
    print
    next
  }
  # Case 1: We are inside a documentation block.
  if (in_xs_doc)
  {
################################################################################
# Checking for the closing tag, capturing optional content before it. Assumes  #
# content on the same line as the tag and does not contain '<'.                #
################################################################################
    if (match($0, /(^\s*)([^<]*)(<\/xs:documentation>)/, m))
    {
      content = m[2]
      sub(/^\s*/, "", content)
      sub(/\s*$/, "", content)
      if (length(content) > 0)
      {
        print xs_doc_indent "  " content
      }

################################################################################
# Printing the correctly indented closing tag.                                 #
################################################################################
      print xs_doc_indent m[3]

      # Reset state.
      in_xs_doc = 0
      xs_doc_indent = ""
    }
    else
    {
# Now we have a line of content inside the block.
      content = $0
# Stripping leading space.
      sub(/^\s*/, "", content)
      if (length(content) > 0)
      {
        print xs_doc_indent "  " content
      }
      else
      {
# Preserving empty lines within the block.
        print
      }
    }
  }
# We are **not** inside a documentation block.
  else
  {
################################################################################
# Checking for the opening tag. The regex captures the tag and any potential   #
# content on the same line.                                                    #
################################################################################
    if (match($0, /(^\s*)(<xs:documentation[^>]*>)(.*)/, m))
    {
      xs_doc_indent = m[1]
      in_xs_doc = 1

# Printing the opening tag.
      print m[1] m[2]

      content = m[3]
# Trimming whitespace from content.
      sub(/^\s*/, "", content)
      sub(/\s*$/, "", content)
      if (length(content) > 0)
      {
        print xs_doc_indent "  " content
      }
    }
    else
    {
# We have a regular line, print it as is.
      print
    }
  }
}
