#!/usr/bin/gawk -f

################################################################################
# Replaces blank lines, that are not within <xs:documentation ...>,            #
# </xs:documentation> with marker.                                             #
################################################################################
BEGIN {
  in_xs_doc=0;
  marker="<!--xxxx-xxxx-xxxx-->"
}

{
  if (0 != match($0, /^\s*<xs:documentation .+=".+">$/))
  {
    in_xs_doc=1;
    printf("%s\n", $0);
  }
  else if (0 != match($0, /^\s*<xs:documentation>$/))
  {
    in_xs_doc=1;
    printf("%s\n", $0);
  }
  else if (0 != match($0, /^\s*<xs:documentation .+=".+">.+[^>]$/))
  {
    in_xs_doc=1;
    printf("%s\n", $0);
  }
  else if (0 != match($0, /^\s*<\/xs:documentation>$/))
  {
    in_xs_doc=0;
    printf("%s\n", $0);
  }
  else if (0 != match($0, /^\s+[^ <].*<\/xs:documentation>$/))
  {
    in_xs_doc=0;
    printf("%s\n", $0);
  }
  else if (0 == length($0))
  {
    if (0 == in_xs_doc)
    {
      printf("%s\n", marker);
    }
    else
    {
      printf("\n");
    }
  }
  else
  {
    printf("%s\n", $0);
  }
}
