#!/bin/bash

cd ..
while IFS= read -r pom
do
  sed -i 's/<!--xxxx-xxxx-xxxx-->//' "${pom}"
  sed -i 's/multi-line-comment-blank-line-marker//' "${pom}"
  xsd/awk2b --include inplace "${pom}"
done <<< "$(find . -type f \( -name "*\.pom" -o -name "pom\.xml" \))"
